In [149]:
import pandas as pd
from typing import List, Dict
data = pd.read_csv('Health_Data_Set.csv')
print(data)

     Symptom 1  Symptom 2  Symptom 3  Symptom 4  Condition
0            1          1          0          0          0
1            0          1          0          0          0
2            0          1          1          0          3
3            1          0          1          1          1
4            1          0          0          0          3
..         ...        ...        ...        ...        ...
200          0          1          1          1          1
201          1          1          1          0          1
202          1          0          0          1          2
203          1          0          0          1          2
204          1          0          0          1          1

[205 rows x 5 columns]


In [150]:

#Normalized data?  


df = pd.DataFrame(data)
print(df.shape)

counts = df.apply(lambda x: x.value_counts(normalize=True)).fillna(0)
 
# Display the counts
print(counts)


(205, 5)
   Symptom 1  Symptom 2  Symptom 3  Symptom 4  Condition
0   0.565854   0.560976   0.604878   0.526829   0.160976
1   0.434146   0.439024   0.395122   0.473171   0.282927
2   0.000000   0.000000   0.000000   0.000000   0.321951
3   0.000000   0.000000   0.000000   0.000000   0.234146


In [151]:
#Normalized data? 

import numpy as np

def analyze_symptoms(df, data, num_symptoms=4):
    ones_array = np.zeros(num_symptoms)
    zeros_array = np.zeros(num_symptoms)
    
    # Calculate values for each symptom
    for i in range(1, num_symptoms + 1):
        symptom_col = f'Symptom {i}'
        counts = df[symptom_col].value_counts()
        
        # Store values in arrays
        ones_array[i-1] = counts[1] / (len(data) * 4)
        zeros_array[i-1] = counts[0] / (len(data) * 4)
        
        # Print results
        print(f"Symptom {i}: {ones_array[i-1]:.4f} - {zeros_array[i-1]:.4f}")
    
    return ones_array, zeros_array

In [255]:
joint = np.zeros((4, 4))

for i in range(4):
    for j in range(4):
        symptom_col = f'Symptom {i + 1}'
        joint[i][j] = np.sum((df[symptom_col] == 1) & (df['Condition'] == j))
        joint[i][j] /= len(data) * 4        


joint_with_zeros = np.zeros((4, 4))

for i in range(4):
    for j in range(4):
        symptom_col = f'Symptom {i + 1}'
        joint_with_zeros[i][j] = np.sum((df[symptom_col] == 0) & (df['Condition'] == j))
        joint_with_zeros[i][j] /= len(data) * 4
#Condition X axis, Symptom Y axis. 
#Joint [1][0] = Symptom -> 2 and Condition -> 0
#Joint [0][1] = Symptom -> 1 and Condition -> 1


In [256]:
print(joint)
print()
print(joint_with_zeros)
print (np.sum(joint) + np.sum (joint_with_zeros))

[[0.01463415 0.03292683 0.04756098 0.01341463]
 [0.00731707 0.03780488 0.02804878 0.03658537]
 [0.00487805 0.03902439 0.03414634 0.02073171]
 [0.0097561  0.04756098 0.03780488 0.02317073]]

[[0.02560976 0.03780488 0.03292683 0.04512195]
 [0.03292683 0.03292683 0.05243902 0.02195122]
 [0.03536585 0.03170732 0.04634146 0.03780488]
 [0.0304878  0.02317073 0.04268293 0.03536585]]
1.0


In [257]:
joint = np.zeros((2, 2, 2, 2, 4))

# Count occurrences
for index, row in df.iterrows():
    s1, s2, s3, s4, condition = row
    joint[int(s1)][int(s2)][int(s3)][int(s4)][int(condition)] += 1

# Normalize the joint probability matrix
joint /= len(data)

# Print the joint probability matrix
print(joint)

[[[[[0.05853659 0.01463415 0.00487805 0.0097561 ]
    [0.0195122  0.03902439 0.00487805 0.03902439]]

   [[0.00487805 0.         0.03902439 0.00487805]
    [0.         0.         0.02926829 0.0097561 ]]]


  [[[0.01463415 0.0097561  0.0097561  0.04390244]
    [0.00487805 0.03902439 0.03414634 0.02439024]]

   [[0.         0.00487805 0.0097561  0.03902439]
    [0.         0.04390244 0.         0.0097561 ]]]]



 [[[[0.02439024 0.00487805 0.03414634 0.0097561 ]
    [0.0097561  0.01463415 0.04390244 0.00487805]]

   [[0.0097561  0.02926829 0.04390244 0.0097561 ]
    [0.00487805 0.02926829 0.0097561  0.        ]]]


  [[[0.0097561  0.         0.02926829 0.01463415]
    [0.         0.00487805 0.02439024 0.00487805]]

   [[0.         0.02926829 0.         0.0097561 ]
    [0.         0.0195122  0.00487805 0.        ]]]]]
